yarnPath: .yarn/releases/yarn-3.3.0.cjs
packageExtensions:
  "@apollo/react-hoc@*":
    peerDependencies:
      apollo-cache: "*"
      apollo-link: "*"
      apollo-utilities: "*"
  "@apollo/react-hooks@*":
    peerDependencies:
      apollo-utilities: "*"
  "@apollo/react-ssr@*":
    peerDependencies:
      apollo-utilities: "*"
      apollo-client: "*"
      graphql: "*"
  "@storybook/addon-docs@*":
    peerDependencies:
      "@babel/core": "*"
      webpack: "*"
  "@storybook/addon-info@*":
    peerDependencies:
      react-dom: "*"
  "@storybook/addon-knobs@*":
    peerDependencies:
      react-dom: "*"
  "@storybook/addons@*":
    peerDependencies:
      react-dom: "*"
  "@storybook/api@*":
    peerDependencies:
      react-dom: "*"
  "@storybook/client-api@*":
    peerDependencies:
      react-dom: "*"
      react: "*"
  "@storybook/docs-tools@*":
    peerDependencies:
      react-dom: "*"
      react: "*"
  "@storybook/mdx1-csf@*":
    peerDependencies:
      "@babel/core": "*"
  "@storybook/telemetry@*":
    peerDependencies:
      react-dom: "*"
      react: "*"
  "@types/storybook__addon-info@*":
    peerDependencies:
      react-dom: "*"
      react: "*"
      require-from-string: "*"
  apollo-link-error@*:
    peerDependencies:
      graphql: "*"
  react-apollo@*:
    peerDependencies:
      apollo-cache: "*"
      apollo-link: "*"
      apollo-utilities: "*"




